-- 1. Create the 'Parent' table first (User)
CREATE TABLE IF NOT EXISTS users
(
    id           int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name   varchar(50) NOT NULL,
    last_name    varchar(50) NOT NULL,
    email        text        NOT NULL UNIQUE,
    phone_number varchar(15) NOT NULL CHECK (char_length(phone_number) >= 11 AND char_length(phone_number) <= 15),
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now()
);

-- 2. Create the 'Child' table second (Address)
CREATE TABLE IF NOT EXISTS addresses
(
    id             int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    -- This is the Foreign Key that connects multiple addresses to one user
    user_id        int8         NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    street_address varchar(100) NOT NULL CHECK (char_length(street_address) >= 5),
    apartment      varchar(50),
    city           varchar(50)  NOT NULL CHECK (char_length(city) >= 2),
    state          varchar(50),
    postal_code    varchar(10)  NOT NULL CHECK (char_length(postal_code) >= 3),
    country_code   varchar(2)   NOT NULL CHECK (char_length(country_code) = 2),
    created_at     timestamptz  NOT NULL DEFAULT now(),
    updated_at     timestamptz  NOT NULL DEFAULT now()
);

-- 3. Add an index to make address lookups by user_id very fast
CREATE INDEX IF NOT EXISTS idx_addresses_user_id ON addresses (user_id);

CREATE TABLE IF NOT EXISTS products
(
    id                         int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name                       varchar(150)  NOT NULL,
    category                   varchar(50)   NOT NULL,
    manufacturer               varchar(150)  NOT NULL,
    price                      decimal(8, 2) NOT NULL CHECK (price >= 0.01),
    cost_price                 decimal(8, 2) NOT NULL CHECK (cost_price >= 0.01),
    sale_price                 decimal(8, 2) CHECK (sale_price >= 0.01),
    currency_code              char(3)       NOT NULL,
    sku                        varchar(30)   NOT NULL UNIQUE,
    quantity_in_stock          int4          NOT NULL DEFAULT 0,
    low_stock_threshold        int4          NOT NULL DEFAULT 1,
    expected_availability_date timestamptz,
    attributes                 jsonb                  DEFAULT '{}',
    image_url                  text,
    status                     varchar(20)   NOT NULL,
    created_at                 timestamptz   NOT NULL DEFAULT now(),
    created_by                 varchar(50)   NOT NULL,
    updated_at                 timestamptz   NOT NULL DEFAULT now(),
    updated_by                 varchar(50),
    version                    int8          NOT NULL DEFAULT 0
);

CREATE INDEX idx_products_sku ON products (sku);
CREATE INDEX idx_products_category ON products (category);